require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TestersController do

  # This should return the minimal set of attributes required to create a valid
  # Tester. As you add validations to Tester, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all testers as @testers" do
      tester = Tester.create! valid_attributes
      get :index
      assigns(:testers).should eq([tester])
    end
  end

  describe "GET show" do
    it "assigns the requested tester as @tester" do
      tester = Tester.create! valid_attributes
      get :show, :id => tester.id.to_s
      assigns(:tester).should eq(tester)
    end
  end

  describe "GET new" do
    it "assigns a new tester as @tester" do
      get :new
      assigns(:tester).should be_a_new(Tester)
    end
  end

  describe "GET edit" do
    it "assigns the requested tester as @tester" do
      tester = Tester.create! valid_attributes
      get :edit, :id => tester.id.to_s
      assigns(:tester).should eq(tester)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tester" do
        expect {
          post :create, :tester => valid_attributes
        }.to change(Tester, :count).by(1)
      end

      it "assigns a newly created tester as @tester" do
        post :create, :tester => valid_attributes
        assigns(:tester).should be_a(Tester)
        assigns(:tester).should be_persisted
      end

      it "redirects to the created tester" do
        post :create, :tester => valid_attributes
        response.should redirect_to(Tester.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tester as @tester" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tester.any_instance.stub(:save).and_return(false)
        post :create, :tester => {}
        assigns(:tester).should be_a_new(Tester)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tester.any_instance.stub(:save).and_return(false)
        post :create, :tester => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tester" do
        tester = Tester.create! valid_attributes
        # Assuming there are no other testers in the database, this
        # specifies that the Tester created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tester.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => tester.id, :tester => {'these' => 'params'}
      end

      it "assigns the requested tester as @tester" do
        tester = Tester.create! valid_attributes
        put :update, :id => tester.id, :tester => valid_attributes
        assigns(:tester).should eq(tester)
      end

      it "redirects to the tester" do
        tester = Tester.create! valid_attributes
        put :update, :id => tester.id, :tester => valid_attributes
        response.should redirect_to(tester)
      end
    end

    describe "with invalid params" do
      it "assigns the tester as @tester" do
        tester = Tester.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tester.any_instance.stub(:save).and_return(false)
        put :update, :id => tester.id.to_s, :tester => {}
        assigns(:tester).should eq(tester)
      end

      it "re-renders the 'edit' template" do
        tester = Tester.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tester.any_instance.stub(:save).and_return(false)
        put :update, :id => tester.id.to_s, :tester => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tester" do
      tester = Tester.create! valid_attributes
      expect {
        delete :destroy, :id => tester.id.to_s
      }.to change(Tester, :count).by(-1)
    end

    it "redirects to the testers list" do
      tester = Tester.create! valid_attributes
      delete :destroy, :id => tester.id.to_s
      response.should redirect_to(testers_url)
    end
  end

end
